using System;
using System.Text;
using AE2Unity;
using UnityEngine;

namespace AE2Unity.Editor
{
    internal static class Ae2ShaderCodeGenerator
    {
        public static string GeneratePreviewShader(Ae2ShaderClip clip, string shaderName)
        {
            var document = clip != null ? clip.Document : null;
            var comp = document?.comp ?? new Ae2ShaderComp();
            var layers = document?.layers ?? Array.Empty<Ae2ShaderLayer>();
            var warnings = clip?.ImportWarnings ?? Array.Empty<string>();

            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by AE2Unity.");
            builder.AppendLine("// This MVP shader is a preview target. Layer/effect compiler passes are added incrementally.");
            builder.AppendLine($"// Source comp: {EscapeComment(comp.name)} ({comp.width}x{comp.height}, {comp.frameRate:0.###} fps, {comp.duration:0.###}s)");
            builder.AppendLine("//");
            builder.AppendLine("// Exported layers:");
            for (var i = 0; i < layers.Length; i++)
            {
                var layer = layers[i];
                if (layer == null)
                {
                    continue;
                }

                builder.AppendLine($"// - {layer.index}: {EscapeComment(layer.name)} [{EscapeComment(layer.type)}], blend={EscapeComment(layer.blendMode)}, opacity={layer.transform?.opacity?.value ?? 100f:0.###}");
            }

            if (warnings.Length > 0)
            {
                builder.AppendLine("//");
                builder.AppendLine("// Import warnings:");
                for (var i = 0; i < warnings.Length; i++)
                {
                    builder.AppendLine($"// - {EscapeComment(warnings[i])}");
                }
            }

            builder.AppendLine($"Shader \"{EscapeShaderPath(shaderName)}\"");
            builder.AppendLine("{");
            builder.AppendLine("    Properties");
            builder.AppendLine("    {");
            builder.AppendLine("        _MainTex (\"Texture\", 2D) = \"white\" {}");
            builder.AppendLine("        _Tint (\"Tint\", Color) = (1, 1, 1, 1)");
            builder.AppendLine("        _Opacity (\"Opacity\", Range(0, 1)) = 1");
            builder.AppendLine("        _AeTime (\"AE Time\", Float) = 0");
            builder.AppendLine($"        _CompSize (\"Comp Size\", Vector) = ({Mathf.Max(1, comp.width)}, {Mathf.Max(1, comp.height)}, {1f / Mathf.Max(1, comp.width):0.########}, {1f / Mathf.Max(1, comp.height):0.########})");
            builder.AppendLine("    }");
            builder.AppendLine("    SubShader");
            builder.AppendLine("    {");
            builder.AppendLine("        Tags { \"RenderPipeline\"=\"UniversalPipeline\" \"Queue\"=\"Transparent\" \"RenderType\"=\"Transparent\" \"IgnoreProjector\"=\"True\" }");
            builder.AppendLine("        Blend SrcAlpha OneMinusSrcAlpha");
            builder.AppendLine("        Cull Off");
            builder.AppendLine("        ZWrite Off");
            builder.AppendLine("        Pass");
            builder.AppendLine("        {");
            builder.AppendLine("            Name \"AE2UnityGeneratedPreview\"");
            builder.AppendLine("            HLSLPROGRAM");
            builder.AppendLine("            #pragma vertex Vert");
            builder.AppendLine("            #pragma fragment Frag");
            builder.AppendLine("            #pragma target 3.0");
            builder.AppendLine("            #include \"Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl\"");
            builder.AppendLine("            struct Attributes { float4 positionOS : POSITION; float2 uv : TEXCOORD0; };");
            builder.AppendLine("            struct Varyings { float4 positionHCS : SV_POSITION; float2 uv : TEXCOORD0; };");
            builder.AppendLine("            TEXTURE2D(_MainTex);");
            builder.AppendLine("            SAMPLER(sampler_MainTex);");
            builder.AppendLine("            CBUFFER_START(UnityPerMaterial)");
            builder.AppendLine("                float4 _MainTex_ST;");
            builder.AppendLine("                half4 _Tint;");
            builder.AppendLine("                half _Opacity;");
            builder.AppendLine("                float _AeTime;");
            builder.AppendLine("                float4 _CompSize;");
            builder.AppendLine("            CBUFFER_END");
            builder.AppendLine("            Varyings Vert(Attributes input)");
            builder.AppendLine("            {");
            builder.AppendLine("                Varyings output;");
            builder.AppendLine("                output.positionHCS = TransformObjectToHClip(input.positionOS.xyz);");
            builder.AppendLine("                output.uv = TRANSFORM_TEX(input.uv, _MainTex);");
            builder.AppendLine("                return output;");
            builder.AppendLine("            }");
            builder.AppendLine("            half4 Frag(Varyings input) : SV_Target");
            builder.AppendLine("            {");
            builder.AppendLine("                half4 color = SAMPLE_TEXTURE2D(_MainTex, sampler_MainTex, input.uv) * _Tint;");
            builder.AppendLine("                color.a *= _Opacity;");
            builder.AppendLine("                return color;");
            builder.AppendLine("            }");
            builder.AppendLine("            ENDHLSL");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("    FallBack Off");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string EscapeShaderPath(string value)
        {
            return string.IsNullOrWhiteSpace(value)
                ? "AE2Unity/Generated"
                : value.Replace("\\", "/").Replace("\"", string.Empty);
        }

        private static string EscapeComment(string value)
        {
            return string.IsNullOrEmpty(value)
                ? string.Empty
                : value.Replace("\r", " ").Replace("\n", " ");
        }
    }
}
